# 精准度和召回率的平衡

In [1]:
import numpy as np
from sklearn import datasets

In [3]:
digits = datasets.load_digits()
X = digits.data
y = digits.target.copy()

y[digits.target == 9] = 1
y[digits.target != 9] = 0

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [5]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
log_reg.score(X_test, y_test)

0.96111111111111114

In [6]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score

In [8]:
y_predict = log_reg.predict(X_test)

print(confusion_matrix(y_test, y_predict))
print(precision_score(y_test, y_predict))
print(recall_score(y_test, y_predict))

[[318   6]
 [  8  28]]
0.823529411765
0.777777777778


In [9]:
decision_score = log_reg.decision_function(X_test)
decision_score.shape

(360,)

In [10]:
print(decision_score.max())
print(decision_score.min())

22.1277301223
-91.9750817428


In [11]:
y_predict_p5 = np.array(decision_score > 5, dtype=int)
print(confusion_matrix(y_test, y_predict_p5))
print(precision_score(y_test, y_predict_p5))
print(recall_score(y_test, y_predict_p5))

[[324   0]
 [ 16  20]]
1.0
0.555555555556


In [13]:
y_predict_m5 = np.array(decision_score > -5, dtype=int)
print(confusion_matrix(y_test, y_predict_m5))
print(precision_score(y_test, y_predict_m5))
print(recall_score(y_test, y_predict_m5))

[[309  15]
 [  3  33]]
0.6875
0.916666666667
