# 08 Scikit-learn中的Scaler

In [1]:
import numpy as np
import sklearn.datasets as datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
iris = datasets.load_iris()
X = iris.data
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [3]:
standardScaler = StandardScaler()
standardScaler.fit(X_train)
X_train_standard = standardScaler.transform(X_train)

In [4]:
print(X_train[:5, :])
print(X_train_standard[:5, :])

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 5.7  2.8  4.1  1.3]
 [ 6.2  3.4  5.4  2.3]
 [ 5.1  2.5  3.   1.1]]
[[-0.90616043  0.94720873 -1.30982967 -1.28485856]
 [-1.15301457 -0.18717298 -1.30982967 -1.28485856]
 [-0.16559799 -0.64092567  0.22169257  0.17345038]
 [ 0.45153738  0.72033239  0.95909217  1.49918578]
 [-0.90616043 -1.3215547  -0.40226093 -0.0916967 ]]


#### 测试数据是模拟真实环境
1. 真实数据可能无法得到所有测试数据的均值和方差
2. 对数据的归一化也是算法的一部分

In [5]:
X_test_standard = standardScaler.transform(X_test)

#### 使用归一化后的数据进行knn分类

In [6]:
from sklearn.neighbors import KNeighborsClassifier

knn_clf = KNeighborsClassifier(n_neighbors=3)
knn_clf.fit(X_train_standard, y_train)
knn_clf.score(X_test_standard, y_test)

1.0

#### 使用自己封装的 StandardScaler

In [7]:
from playML.preprocessing import StandardScaler
standardScaler = StandardScaler()
standardScaler.fit(X_train)
X_train_standard = standardScaler.transform(X_train)
X_test_standard = standardScaler.transform(X_test)

In [8]:
knn_clf = KNeighborsClassifier(n_neighbors=3)
knn_clf.fit(X_train_standard, y_train)
knn_clf.score(X_test_standard, y_test)

1.0